name: Workflow CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -nowarn:CS8618,CS8766,CS8603,CS8625,CS8604

    - name: Run unit tests
      run: dotnet test Contatos.Testes/Contatos.Testes.csproj --filter "Category=Unit"

    - name: Run integration tests
      run: dotnet test Contatos.Testes/Contatos.Testes.csproj --filter "Category=Integration"

    - name: Publish
      run: dotnet publish -c Release --property:PublishDir=Publish -nowarn:CS8618,CS8766,CS8603,CS8625,CS8604
